### ISSUE TITLE
Update to new version :c

### ISSUE THREAD

**Issue by TheNarratorX** [HAWGT/GGST-Enhancer#10]
I really want the Update ... for the new version of the game :c

**Comment by HAWGT** [comment]
it's already updated

**Comment by Energyblast** [comment]
I assume the update broke the EX color, then? The custom avatar was a nice add.

**Comment by HAWGT** [comment]
broke "invalid" colors

**Comment by TheNarratorX** [comment]
The survival colors dont work anymore :c

**Comment by HAWGT** [comment]
Closing this as I have no current plans on researching how to restore the color functionality.
