### ISSUE TITLE
New Version Update

### ISSUE THREAD

**Issue by genericname02** [HAWGT/GGST-Enhancer#3]
New Version Memory Addresses changed., but I would like to know how you are getting the byte array of each color if it is inaccessible,,?? What I mean by this is that you arent able to select the color so how did you find the bytes for them

**Comment by HAWGT** [comment]
I just used cheat engine with veh debugger so it doesn't crash (steam drm I believe), I changed colors, searched for values within the 0-10 range, right click -> find what writes to the address, looked at the assembly instructions and patched them (a bit of trial and error to get the PSN color patch right).

The bytes don't represent the colors, they are assembly instructions for when you change color.

**Comment by HAWGT** [comment]
Updated
