### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by genericname02** [HAWGT/GGST-Enhancer#4]
Hello Again!! I am currently Working on unlocking Crawl || This song is the arcade boss fight song. Hopefully I can figure it out and would like to share with you once I do.

**Comment by HAWGT** [comment]
I would suggest looking into the ADD & SUB instructions and going from there, trying to eliminate the checks for unobtainables.

**Comment by genericname02** [comment]
The Song 101, is an obtainable ive seen someone else using it already :) 
its the same as jack o 17, its there you cant see it unless you have the character but you can still unlock it if you so very wish, I also found various colors for Characters. Here is one for you its pretty funny, go to ram and select color 24 (23 in Cheat Engine)
