### ISSUE TITLE
New Version Update

### ISSUE THREAD

**Issue by transientnight** [HAWGT/GGST-Enhancer#5]
Hello,

Doesn't seem to be working with new version.

**Comment by genericname02** [comment]
> Hello,
> 
> Doesn't seem to be working with new version.

uh... duh, address have changed so you need to find new pointers its not that hard to do.. it just takes a while

**Comment by HAWGT** [comment]
@transientnight @genericname02 
New release, it doesn't take more than 10 minutes, I just have been busy with other stuff.
